// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poooseaagaqbebhuasjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvb29zZWFhZ2FxYmViaHVhc2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzY0MjEsImV4cCI6MjA2MjYxMjQyMX0.L_NUprRzTOHcdmeoPLUSAo_A1VJm2sXPZZ50oJkSbDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);